###USERS!!!!!!!!!!!!!!!!!!!!!!!

POST http://localhost:8081/user/auth
Content-Type: application/json

{
  "login": "user",
  "password": "user123"
}

###
POST http://localhost:8081/user/logout
Content-Type: application/json

{
  "login": "user",
  "password": "user123",
  "token": "567395058"

}

###

GET http://localhost:8081/user/all
Content-Type: application/json


###

GET http://localhost:8081/user/8
Content-Type: application/json

{
  "token": "-1464266702"
}
###

POST http://localhost:8081/user/reg
Content-Type:application/json

{
  "id": 1,
  "login": "user",
  "password": "user123",
  "balance": 50000,
  "name": "Vova",
  "age": 22,
  "address": "Kolcova 15-22",
  "email": "Vovabooks@mail.ru"

}
###

DELETE http://localhost:8081/user/delete/8
Content-Type: application/json


###

PUT http://localhost:8081/user/update
Content-Type: application/json

{
  "id": 1,
  "login": "user",
  "password": "user123",
  "balance": 5006,
  "name": "Vika111111",
  "age": 32,
  "address": "Pyshkina 47",
  "email": "Vikabooks@mail.ru",
  "token": "-1464266702"

}
###            BOOOKS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

GET http://localhost:8081/book/all
Content-Type: application/json
###

GET http://localhost:8081/book/4
Content-Type: application/json
###

POST http://localhost:8081/book/add
Content-Type:application/json

{
  "title": "Maary Barbara Hamilton Cartland",
  "author": "Barbara Kartlend",
  "bookGenre": 3,
  "price": 120,
  "raiting": 1

}
###

DELETE http://localhost:8081/book/delete/19
Content-Type: application/json

###

PUT http://localhost:8081/book/update
Content-Type: application/json

{
  "bookId": 18,
  "title": "1Mary Barbara Hamilton Cartland",
  "author": "Barbara Kartlend",
  "bookGenre": 3,
  "price": 100,
  "raiting": 0

}

###               BASKET!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GET http://localhost:8081/basket/getAll
Content-Type: application/json

{
  "token": "-1464266702"
}

###

POST http://localhost:8081/basket/addBasket
Content-Type: application/json

{
  "id": 1,
  "idBooks": 2,
  "totalCost": 76
}

###
DELETE http://localhost:8081/basket/delete/17
Content-Type: application/json


### ORDERS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

GET http://localhost:8081/order/all
Content-Type: application/json

{
  "token": "-1464266702"
}

###
POST http://localhost:8081/order/add
Content-Type: application/json

{
  "idUser":1,
  "idBasket": 18,
  "phone": "+375-29-111-11-11",
  "totalPrice": 76,
  "status": 0

}

###

GET http://localhost:8081/order/2
Content-Type: application/json

{
  "token": "-1464266702"
}

###
DELETE http://localhost:8081/order/delete/1
Content-Type: application/json


###
PUT http://localhost:8081/order/update
Content-Type: application/json

{
  "idOrder":2,
  "idUser":1,
  "idBasket":18,
  "totalPrice": 121,
  "phone": "+375-29-111-11-11",
  "status":0

}
###

POST http://localhost:8081/order/sent
Content-Type: application/json

{
  "idOrder":2,
  "idUser":1,
  "idBasket":18,
  "phone": "+375-29-111-11-11",
  "status": 1

}

###


